### PR TITLE
Extended app for clockwise polygons

### PR DESCRIPTION
**Pull request by Rajalo**
Added some functions for extending the function to clockwise-oriented polygons
orientation()- finds orientation of polygon
InConeClockwise- same as inCone but assumes polygon is clockwise instead
DiagonalClockwise- same as Diagonal but assumes polygon is clockwise instead, using InConeClockwise.
recurFindClockwise- same as recurFind but assumes polygon is clockwise instead.

### CODE REVIEW

**Comment by peiliou** [comment]
Thank you Reilly! I feel like the tricky part here is that, InConeClockwise, DiagonalClockwise, recurFindClockwise have 95% of the same code that's in other functions. Orientation() is probably the only method that's making a real difference. 

Initially I would say maybe we can add a clockwise parameter into those 3 original functions, but that gives a huge overhead in the recursive stacks. A better way is to use a global condition flag(using UseRef) so only one variable is used to check the orientation by many function calls.

Please let me know what you think or if there is another idea, great work!

**Comment by Rajalo** [comment]
You're 100% correct and that sounds like a good idea. We can set the global "orientation" flag as default true and then update it every call to "countTriangulations()".

**Comment by peiliou** [comment]
I have made a significant change based on this idea and your code, and with a new feature(undo using ESC at any time). Let me know if you think it is bug-free

**Comment by Rajalo** [comment]
sorry I was working at the same time, I accepted all incoming for the merge

**Comment by Rajalo** [comment]
The ESC undo is a great feature

**Comment by peiliou** [comment]
https://github.com/peiliou/Simple-Polygon-Triangulation-Counting-Tool/compare/main...clockwiseExtension

Check out this comparison, we didn't add much to make it work (found no bugs as of now)

**Comment by peiliou** [comment]
Yeah, it looks correct to me. We can definitely merge it now if you find no other issues. (I'm not sure since it's not thoroughly tested)

**Review by peiliou — APPROVED** [review]

**Comment by peiliou** [comment]
I'm fairly certain it's fine:
image
image

both give the same answer.

**Pull request merged**
